# -*- coding: utf-8 -*-
"""untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/gnorris14/ac6ca9642917e0cbeeada6463f334d41/untitled1.ipynb
"""

#Gavin Norris
#this data shows the average amount per year of PM2.5 for different time periods
#3/5/24
#the dataset is of mutliple different sets of data of air pollution and data related to air pollution over different amounts of time
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
!pip install geopandas
import geopandas as gpd

airQuality = pd.read_csv("https://raw.githubusercontent.com/gnorris14/APCSP/main/Air_Quality.csv")

airQuality = airQuality.rename(columns={'Data Value': 'Data_Value'})

airQuality.groupby(['Name'])
airQuality.groupby(['Time Period'])
PM = airQuality.query('Name == "Fine particles (PM 2.5)"')

PM.hist(column='Data_Value',by='Time Period', figsize = (16,18)) #histogram of averages amounts of PM2.5 per year and its interesting that the amount of PM2.5 has decreased in recent years

#average PM2.5 for all data
airQuality.Data_Value.mean() #the amount of PM2.5 has decreased greatly since 2009

airQuality #all data

airQuality.shape #number of data

#graph of PM2.5 for different dates and this shows theres more data for some years than other years
x1 = airQuality['Data_Value']
y1 = airQuality['Start_Date']
plt.scatter(x1, y1)
plt.title('Average PM2.5')
plt.grid()
plt.xlabel("average PM2.5")
plt.ylabel("Date");
plt.show()